//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eShopFinalProject.Utilities.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("eShopFinalProject.Utilities.Resources.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account does not exist.
        /// </summary>
        public static string Account_Not_Exist {
            get {
                return ResourceManager.GetString("Account_Not_Exist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creating.
        /// </summary>
        public static string Action_Create {
            get {
                return ResourceManager.GetString("Action_Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleting.
        /// </summary>
        public static string Action_Delete {
            get {
                return ResourceManager.GetString("Action_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Getting.
        /// </summary>
        public static string Action_Get {
            get {
                return ResourceManager.GetString("Action_Get", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updating.
        /// </summary>
        public static string Action_Update {
            get {
                return ResourceManager.GetString("Action_Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} {1} Is Failed.
        /// </summary>
        public static string ActionFail_Template {
            get {
                return ResourceManager.GetString("ActionFail_Template", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brand is already in use.
        /// </summary>
        public static string Brand_Existed {
            get {
                return ResourceManager.GetString("Brand_Existed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category is already in use.
        /// </summary>
        public static string Category_Existed {
            get {
                return ResourceManager.GetString("Category_Existed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Color is already in use.
        /// </summary>
        public static string Color_Existed {
            get {
                return ResourceManager.GetString("Color_Existed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coupon is already in use.
        /// </summary>
        public static string Coupon_Existed {
            get {
                return ResourceManager.GetString("Coupon_Existed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creating {0} success.
        /// </summary>
        public static string Create_Succes_Template {
            get {
                return ResourceManager.GetString("Create_Succes_Template", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete {0} success.
        /// </summary>
        public static string Delete_Succes_Template {
            get {
                return ResourceManager.GetString("Delete_Succes_Template", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Getting {0} Is Failed.
        /// </summary>
        public static string GetFailed_Template {
            get {
                return ResourceManager.GetString("GetFailed_Template", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your password is incorrect.
        /// </summary>
        public static string Incorrect_Password {
            get {
                return ResourceManager.GetString("Incorrect_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is not found.
        /// </summary>
        public static string NotFound_Template {
            get {
                return ResourceManager.GetString("NotFound_Template", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product&apos;s name is already in use.
        /// </summary>
        public static string Product_Existed {
            get {
                return ResourceManager.GetString("Product_Existed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blog.
        /// </summary>
        public static string Resource_Blog {
            get {
                return ResourceManager.GetString("Resource_Blog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brand.
        /// </summary>
        public static string Resource_Brand {
            get {
                return ResourceManager.GetString("Resource_Brand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category.
        /// </summary>
        public static string Resource_Category {
            get {
                return ResourceManager.GetString("Resource_Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Color.
        /// </summary>
        public static string Resource_Color {
            get {
                return ResourceManager.GetString("Resource_Color", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coupon.
        /// </summary>
        public static string Resource_Coupon {
            get {
                return ResourceManager.GetString("Resource_Coupon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enquiry.
        /// </summary>
        public static string Resource_Enq {
            get {
                return ResourceManager.GetString("Resource_Enq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order.
        /// </summary>
        public static string Resource_Order {
            get {
                return ResourceManager.GetString("Resource_Order", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product.
        /// </summary>
        public static string Resource_Product {
            get {
                return ResourceManager.GetString("Resource_Product", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product review.
        /// </summary>
        public static string Resource_ProductRating {
            get {
                return ResourceManager.GetString("Resource_ProductRating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User.
        /// </summary>
        public static string Resource_User {
            get {
                return ResourceManager.GetString("Resource_User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update {0} success.
        /// </summary>
        public static string Update_Succes_Template {
            get {
                return ResourceManager.GetString("Update_Succes_Template", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image upload failed.
        /// </summary>
        public static string UploadImage_Failed {
            get {
                return ResourceManager.GetString("UploadImage_Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot change email.
        /// </summary>
        public static string User_Cannot_Change_Email {
            get {
                return ResourceManager.GetString("User_Cannot_Change_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email is already in use.
        /// </summary>
        public static string UserEmail_Existed {
            get {
                return ResourceManager.GetString("UserEmail_Existed", resourceCulture);
            }
        }
    }
}
